* Numpy arrays have two type: 1-D (Vectors) and 2-D (Matrices)

###### Use Numpy array over 'standard' python list because :

1. Memory Efficient
2. Easily expandable of N-dimensions
3. Better speed of calculations
4. Broadcasting operations and functions with Numpy
5. All other ML , DL, CV and DS libraries are built on top of NumPy  


#### Importing Numpy

In [1]:
import numpy as np #alias

In [3]:
# Creating an array by directly converting a list or list of lists

my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Built-in Methods to create Arrays

In [7]:
# arange : returns evenly spaced values within a given interval

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(20,35)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [10]:
np.arange(17)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [12]:
np.arange(20,35,7)

array([20, 27, 34])

In [13]:
#zeros and ones : Generate arrays of zeros and ones

In [14]:
np.zeros(4)

array([0., 0., 0., 0.])

In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
#linspace : returns evenly spaced numbers over a specifield interval 
#(inclusive of both the limits)

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [22]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [23]:
#eye : create an identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Random

In [25]:
#rand : creates an array of the given shape and populates it with random samples from 
# a uniform distribution over [0,1)

In [69]:
np.random.rand(2)

array([0.73869806, 0.19652406])

In [70]:
np.random.rand(3,4)

array([[0.90035817, 0.16229456, 0.25338712, 0.55261699],
       [0.96453687, 0.62646867, 0.7961393 , 0.89442739],
       [0.14135483, 0.50604965, 0.88295196, 0.70933588]])

In [71]:
#randn : returns a sample(s) from 'standard normal' distribution (sigma=1).
# Unlike rand which is uniform, values here closer to zero

In [79]:
np.random.randn(3)

array([-0.43725392, -0.35379198, -0.79260867])

In [80]:
np.random.randn(3,4)

array([[ 0.62976659,  0.83994163,  0.81354641, -1.05135759],
       [-1.90230563, -0.01176556, -0.49800459, -1.25762059],
       [-0.63467223, -0.29378323,  1.64902415, -0.16904635]])

In [81]:
#randint : return random integers from low (inclusive) to high (exclusive)

np.random.randint(1,10)

9

In [75]:
np.random.randint(1,100,20)

array([88, 24, 97, 75, 77, 77, 84,  8, 22, 45, 10, 74, 37, 95, 13, 63, 36,
       25, 83, 53])

In [78]:
np.random.randint(1000,20000,(4,4))

array([[18804,  3111, 15848,  2829],
       [ 8977,  1982,  1089, 16663],
       [ 7101, 12825, 16754,  5201],
       [ 7603,  4618,  6495, 14736]])

In [90]:
# seed : used to set the random state, so that the same 'random' numbers can be reproduced

np.random.seed(90)
np.random.randint(101,900,(3,4))

array([[770, 727, 772, 424],
       [780, 553, 671, 503],
       [175, 581, 208, 536]])

#### Array Attributes and Methods

In [92]:
arr = np.arange(25)

In [93]:
ranarr = np.random.randint(0,50,10)

In [94]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [95]:
ranarr

array([30, 16, 18, 13, 18,  9,  0,  0, 10, 31])

In [96]:
#shape

arr.shape

(25,)

In [97]:
ranarr.shape

(10,)

In [98]:
arr2 = np.random.randint(0,50,(4,3))

In [99]:
arr2

array([[40, 48, 43],
       [12,  4, 26],
       [ 9, 48,  6],
       [11, 16, 15]])

In [100]:
arr2.shape

(4, 3)

In [102]:
#reshape: return an array containing the same data with a new shape

arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [103]:
arr2.reshape(3,4)

array([[40, 48, 43, 12],
       [ 4, 26,  9, 48],
       [ 6, 11, 16, 15]])

In [104]:
arr2

array([[40, 48, 43],
       [12,  4, 26],
       [ 9, 48,  6],
       [11, 16, 15]])

In [105]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [106]:
arr.shape

(25,)

In [110]:
changed_arr = arr.reshape(1,25)
changed_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [111]:
changed_arr.shape

(1, 25)

In [113]:
changed_arr1 = arr.reshape(25,1)

In [115]:
changed_arr1.shape

(25, 1)