In [44]:
import numpy as np

In [45]:
arr = np.arange(11,42,2)
arr

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41])

###### Bracket Indexing and Selection

In [46]:
#Get a value at an index
arr[3]

17

In [47]:
arr[-3]

37

In [48]:
#Get a values between indices

arr[2:6]

array([15, 17, 19, 21])

In [49]:
arr[-5:]

array([33, 35, 37, 39, 41])

In [50]:
arr[:6]

array([11, 13, 15, 17, 19, 21])

###### Broadcasting

In [51]:
arr[:5] = 100

In [52]:
arr

array([100, 100, 100, 100, 100,  21,  23,  25,  27,  29,  31,  33,  35,
        37,  39,  41])

In [53]:
arr = np.arange(11,42,2)
arr

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41])

In [54]:
slice_of_arr = arr[:5]
slice_of_arr

array([11, 13, 15, 17, 19])

In [55]:
slice_of_arr

array([11, 13, 15, 17, 19])

In [56]:
slice_of_arr[:] = 99

In [57]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [58]:
arr

array([99, 99, 99, 99, 99, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41])

###### DATA IS NOT COPIED

* Slice is just a view of the original array. This avoids memory issues

In [59]:
arr = np.arange(11,42,2)
arr

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41])

In [60]:
arr_copy = arr.copy()

In [61]:
slice_of_arr = arr_copy[:5]
slice_of_arr

array([11, 13, 15, 17, 19])

In [62]:
slice_of_arr[:] = 90

In [63]:
arr_copy

array([90, 90, 90, 90, 90, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41])

In [64]:
arr

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41])

###### in case of Standard Lists

In [65]:
l1 = [1,2,3,4,5]

In [66]:
l2 = l1[:3]

In [67]:
l2

[1, 2, 3]

In [68]:
l2[0] = 101

In [69]:
l2

[101, 2, 3]

In [70]:
l1

[1, 2, 3, 4, 5]

#### Indexing a 2D array (matrices)

In [71]:
arr_2d = np.array(([5,10,15],[20,25,35],[40,42,47]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 35],
       [40, 42, 47]])

In [72]:
arr_2d[0]

array([ 5, 10, 15])

In [73]:
arr_2d[2]

array([40, 42, 47])

In [74]:
arr_2d[-1]

array([40, 42, 47])

In [75]:
arr_2d[-3]

array([ 5, 10, 15])

In [76]:
arr_2d[2][2]

47

In [77]:
arr_2d[2][-1]

47

In [78]:
arr_2d[-1][2]

47

In [79]:
arr_2d[-1][-1]

47

In [80]:
arr_2d[1][0]

20

In [81]:
arr_2d[1,0]

20

###### Slicing

In [83]:
arr_2d = np.arange(11,50,2).reshape(5,4)
arr_2d

array([[11, 13, 15, 17],
       [19, 21, 23, 25],
       [27, 29, 31, 33],
       [35, 37, 39, 41],
       [43, 45, 47, 49]])

In [84]:
arr_2d[1:4,1:3]

array([[21, 23],
       [29, 31],
       [37, 39]])

In [87]:
arr_2d[-4:-1,-3:-1]

array([[21, 23],
       [29, 31],
       [37, 39]])

In [88]:
arr_2d[:,1:3]

array([[13, 15],
       [21, 23],
       [29, 31],
       [37, 39],
       [45, 47]])

In [90]:
arr_2d[:,-1]

array([17, 25, 33, 41, 49])

In [92]:
arr_2d[4,:]

array([43, 45, 47, 49])

In [93]:
arr_2d[4,1:3]

array([45, 47])

In [94]:
arr_2d

array([[11, 13, 15, 17],
       [19, 21, 23, 25],
       [27, 29, 31, 33],
       [35, 37, 39, 41],
       [43, 45, 47, 49]])

In [96]:
arr_2d[::3,::2]

array([[11, 15],
       [35, 39]])

In [100]:
arr_2d[1::2,1::2]

array([[21, 25],
       [37, 41]])

###### Conditional Selection

In [102]:
arr = np.arange(3,31,2)
arr

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [103]:
arr > 10

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [104]:
bool_arr = arr > 10

In [106]:
arr[bool_arr == True]

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [107]:
arr[bool_arr == False]

array([3, 5, 7, 9])

In [108]:
arr[bool_arr]

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [110]:
arr[arr<10]

array([3, 5, 7, 9])

#### Summary Statistics on Arrays

In [111]:
arr

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [112]:
arr.sum()

224

In [113]:
arr.mean()

16.0

In [114]:
arr.max()

29

In [115]:
arr.min()

3

In [116]:
arr.var()

65.0

In [117]:
arr.std()

8.06225774829855

#### Axis Logic

* axis 0 : Vertical Axis (rows)
* axis 1 : Horizontal axis (columns)

In [124]:
arr_2d = arr[:-2].reshape(3,4)
arr_2d

array([[ 3,  5,  7,  9],
       [11, 13, 15, 17],
       [19, 21, 23, 25]])

In [125]:
arr_2d.sum()

168

In [126]:
arr_2d.sum(axis=0)

array([33, 39, 45, 51])

In [127]:
arr_2d.sum(axis=1)

array([24, 56, 88])

In [129]:
arr_2d.var(axis=0)

array([42.66666667, 42.66666667, 42.66666667, 42.66666667])